/**
 * SAR-Style Report Service
 * ===========================
 * Feature: SAR-style exportable reports. "SAR" = Suspicious Activity
 * Report, the FinCEN filing US financial institutions submit for
 * activity they suspect is money laundering or fraud. This does NOT
 * generate an actual regulatory filing — that has a specific legal
 * format (FinCEN Form 111) and must go through an institution's real
 * BSA/AML compliance process. What this generates is an internal
 * compliance-review DOCUMENT, formatted the way a real SAR narrative
 * reads, that pulls together everything an investigator (or an
 * institution's own SAR-filing team) would otherwise have to gather by
 * hand from five different screens: the transaction, why it was
 * flagged (hard rules / SHAP / network), how it was resolved, its
 * dispute/chargeback status, and the full audit trail of who touched
 * the case. A clear disclaimer to that effect appears on every export
 * (see FOOTER_DISCLAIMER below) — this is a well-known category of
 * feature where overclaiming ("automated SAR filing") would be actively
 * misleading to a compliance team.
 *
 * Two renderers, one shared data-gathering step (buildCaseData), same
 * "one source of truth, multiple output formats" pattern as
 * transactionRepository feeding both the JSON API and CSV export.
 */

const PDFDocument = require('pdfkit');
const alertRepository = require('../models/alertRepository');
const transactionRepository = require('../models/transactionRepository');
const disputeRepository = require('../models/disputeRepository');
const auditLogRepository = require('../models/auditLogRepository');
const networkRepository = require('../models/networkRepository');
const csvService = require('../services/csvService');

const FOOTER_DISCLAIMER =
  'Generated by FraudGuard for internal compliance review. This is NOT a completed regulatory ' +
  'filing (e.g. FinCEN Form 111) — an institution\'s BSA/AML team must review and file through its ' +
  'own compliance process.';

/**
 * Gathers everything about one case (an alert + its transaction) into a
 * flat, presentation-ready object. Read-only, on-demand — no data is
 * cached or persisted by this step; see routes/admin.js for where it's
 * called from.
 */
async function buildCaseData(alertId) {
  const rawAlert = await alertRepository.findByIdWithDetails(alertId);
  if (!rawAlert) return null;

  const alert = transactionRepository.parseRow(rawAlert); // JSON-parses fraud_reasons/shap_explanation/hard_flag_triggered

  const [dispute, auditTrail, rings] = await Promise.all([
    disputeRepository.findByTransactionId(alert.transaction_id),
    auditLogRepository.forTarget('alert', alertId),
    // Network ring lookup (feature: network/graph fraud ring detection)
    // — same "rebuild the graph" cost caveat as networkRepository.js
    // documents; acceptable here since this is an on-demand compliance
    // export, not a per-transaction hot path.
    networkRepository.detectRings({ minSize: 2 }),
  ]);

  const ring = rings.find((r) => r.members.some((m) => m.user_id === alert.user_id)) || null;

  return {
    alert_id: alert.id,
    generated_at: new Date().toISOString(),
    account: { user_id: alert.user_id, username: alert.username },
    transaction: {
      id: alert.transaction_id,
      merchant: alert.merchant,
      amount: alert.amount,
      category: alert.category,
      location: alert.location,
      card_type: alert.card_type,
    },
    scoring: {
      risk_level: alert.risk_level,
      fraud_score: alert.fraud_score,
      scoring_method: alert.scoring_method,
      hard_flags: alert.hard_flag_triggered || [],
      fraud_reasons: alert.fraud_reasons || [],
      top_shap_factors: (alert.shap_explanation || []).slice(0, 5),
      plain_language_explanation: alert.plain_language_explanation || null,
    },
    network: ring
      ? { in_ring: true, ring_size: ring.size, ring_risk: ring.risk, confirmed_fraud_members: ring.confirmed_fraud_members }
      : { in_ring: false },
    disposition: {
      status: alert.status,
      verdict: alert.verdict || null,
      resolution_note: alert.resolution_note || null,
      assignee: alert.assignee_username || null,
      resolved_at: alert.resolved_at || null,
    },
    dispute: dispute
      ? {
          status: dispute.status, amount_disputed: dispute.amount_disputed, reason: dispute.reason,
          evidence_note: dispute.evidence_note, resolution_note: dispute.resolution_note,
          opened_at: dispute.opened_at, resolved_at: dispute.resolved_at,
        }
      : null,
    audit_trail: auditTrail.map((a) => ({ action: a.action, username: a.username, outcome: a.outcome, created_at: a.created_at })),
  };
}

/** Two-column key/value CSV — a SAR export is a document, not a table
 * of many similar rows, so this reads better than one wide row. Reuses
 * csvService's RFC 4180 escaping rather than hand-rolling it again. */
function toCsv(caseData) {
  const rows = [
    { field: 'Alert ID', value: caseData.alert_id },
    { field: 'Generated At', value: caseData.generated_at },
    { field: 'Account Username', value: caseData.account.username },
    { field: 'Account User ID', value: caseData.account.user_id },
    { field: 'Transaction ID', value: caseData.transaction.id },
    { field: 'Merchant', value: caseData.transaction.merchant },
    { field: 'Amount', value: caseData.transaction.amount },
    { field: 'Category', value: caseData.transaction.category },
    { field: 'Location', value: caseData.transaction.location },
    { field: 'Card Type', value: caseData.transaction.card_type },
    { field: 'Risk Level', value: caseData.scoring.risk_level },
    { field: 'Fraud Score', value: caseData.scoring.fraud_score },
    { field: 'Scoring Method', value: caseData.scoring.scoring_method },
    { field: 'Hard Flags', value: caseData.scoring.hard_flags.join('; ') },
    { field: 'Fraud Reasons', value: caseData.scoring.fraud_reasons.join('; ') },
    { field: 'Top SHAP Factors', value: caseData.scoring.top_shap_factors.map((f) => `${f.feature} (${f.effect})`).join('; ') },
    { field: 'Plain-Language Explanation', value: caseData.scoring.plain_language_explanation },
    { field: 'Part of a Fraud Ring', value: caseData.network.in_ring ? `Yes (size ${caseData.network.ring_size}, risk ${caseData.network.ring_risk})` : 'No' },
    { field: 'Case Status', value: caseData.disposition.status },
    { field: 'Verdict', value: caseData.disposition.verdict },
    { field: 'Resolution Note', value: caseData.disposition.resolution_note },
    { field: 'Assignee', value: caseData.disposition.assignee },
    { field: 'Dispute Status', value: caseData.dispute ? caseData.dispute.status : 'No dispute filed' },
    { field: 'Dispute Amount', value: caseData.dispute ? caseData.dispute.amount_disputed : null },
    { field: 'Audit Trail Entries', value: caseData.audit_trail.length },
    { field: 'Disclaimer', value: FOOTER_DISCLAIMER },
  ];
  return csvService.toCsv(rows, [{ key: 'field', header: 'Field' }, { key: 'value', header: 'Value' }]);
}

/** Renders the same case data as a formatted PDF narrative. Returns a
 * Promise<Buffer> — pdfkit is a stream writer, not a synchronous
 * to-buffer call, so the caller awaits this rather than getting bytes
 * back directly. */
function toPdfBuffer(caseData) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(16).font('Helvetica-Bold').text('Suspicious Activity Report — Internal Compliance Export');
    doc.fontSize(9).font('Helvetica').fillColor('#555').text(FOOTER_DISCLAIMER, { width: 500 });
    doc.moveDown(1);
    doc.fillColor('#000');

    doc.fontSize(10).text(`Case (Alert) ID: ${caseData.alert_id}`);
    doc.text(`Generated: ${caseData.generated_at}`);
    doc.moveDown(0.5);

    section(doc, 'Subject Account');
    kv(doc, [['Username', caseData.account.username], ['User ID', caseData.account.user_id]]);

    section(doc, 'Transaction');
    kv(doc, [
      ['Transaction ID', caseData.transaction.id],
      ['Merchant', caseData.transaction.merchant],
      ['Amount', `$${Number(caseData.transaction.amount).toFixed(2)}`],
      ['Category', caseData.transaction.category],
      ['Location', caseData.transaction.location],
      ['Card Type', caseData.transaction.card_type],
    ]);

    section(doc, 'Narrative of Suspicious Activity');
    doc.fontSize(10).font('Helvetica').text(narrative(caseData), { width: 500 });
    doc.moveDown(0.3);
    kv(doc, [
      ['Risk Level', caseData.scoring.risk_level],
      ['Fraud Score', `${caseData.scoring.fraud_score}/100`],
      ['Scoring Method', caseData.scoring.scoring_method],
    ]);
    if (caseData.scoring.hard_flags.length) bulletList(doc, 'Hard rule flags:', caseData.scoring.hard_flags);
    if (caseData.scoring.fraud_reasons.length) bulletList(doc, 'Fraud reasons:', caseData.scoring.fraud_reasons);
    if (caseData.network.in_ring) {
      doc.fontSize(10).text(
        `Network signal: this account is linked, via shared device/IP, to a cluster of ${caseData.network.ring_size} accounts ` +
        `(risk: ${caseData.network.ring_risk}${caseData.network.confirmed_fraud_members.length ? `, includes confirmed-fraud account(s): ${caseData.network.confirmed_fraud_members.join(', ')}` : ''}).`,
        { width: 500 }
      );
    }

    section(doc, 'Disposition');
    kv(doc, [
      ['Case Status', caseData.disposition.status],
      ['Verdict', caseData.disposition.verdict || 'Not yet resolved'],
      ['Assignee', caseData.disposition.assignee || 'Unassigned'],
      ['Resolved At', caseData.disposition.resolved_at || '—'],
    ]);
    if (caseData.disposition.resolution_note) doc.fontSize(10).text(`Resolution note: ${caseData.disposition.resolution_note}`, { width: 500 });

    section(doc, 'Dispute / Chargeback');
    if (caseData.dispute) {
      kv(doc, [
        ['Status', caseData.dispute.status],
        ['Amount Disputed', `$${Number(caseData.dispute.amount_disputed).toFixed(2)}`],
        ['Reason', caseData.dispute.reason || '—'],
        ['Opened At', caseData.dispute.opened_at],
        ['Resolved At', caseData.dispute.resolved_at || '—'],
      ]);
    } else {
      doc.fontSize(10).text('No dispute has been filed on this transaction.');
    }

    section(doc, 'Audit Trail');
    if (caseData.audit_trail.length === 0) {
      doc.fontSize(10).text('No audit log entries for this case.');
    } else {
      for (const entry of caseData.audit_trail) {
        doc.fontSize(9).text(`${entry.created_at} — ${entry.username || 'system'} — ${entry.action} (${entry.outcome})`);
      }
    }

    doc.end();
  });
}

function section(doc, title) {
  doc.moveDown(0.6);
  doc.fontSize(12).font('Helvetica-Bold').text(title);
  doc.font('Helvetica');
}

function kv(doc, pairs) {
  doc.fontSize(10);
  for (const [label, value] of pairs) {
    doc.text(`${label}: ${value === null || value === undefined ? '—' : value}`);
  }
}

function bulletList(doc, label, items) {
  doc.fontSize(10).text(label);
  for (const item of items) doc.fontSize(10).text(`  •  ${item}`, { width: 480 });
}

function narrative(caseData) {
  if (caseData.scoring.plain_language_explanation) return caseData.scoring.plain_language_explanation;
  if (caseData.scoring.fraud_reasons.length > 0) return caseData.scoring.fraud_reasons.join(' ');
  return 'No specific risk factors were recorded for this transaction.';
}

module.exports = { buildCaseData, toCsv, toPdfBuffer, FOOTER_DISCLAIMER };
